- become: no
  name: K8S Master Init
  user: root
  hosts: master
  tasks:

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ ansible_host }}" --node-name k8s-master --pod-network-cidr=192.168.0.0/16 --apiserver-cert-extra-sans=""{{ ansible_host }}""

  - name: Move the config files from K8S
    shell:
      cmd: |
       mkdir -p $HOME/.kube
       sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
       sudo chown $(id -u):$(id -g) $HOME/.kube/config
       
  - name: Generate join command
    command: kubeadm token create --print-join-command 
    register: join_command

  - name: Copy join command to local file 
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- import_playbook: token-install.yaml
  

